version: 2
ethernets:
  __INTERFACE_NAME__:
    match:
      macaddress: "__MAC_ADDRESS__"
    set-name: __INTERFACE_NAME__
    dhcp4: false
    dhcp6: false
    optional: true
    addresses:
      - "__IP_CIDR__"
    routes:
      - to: default
        via: "__GATEWAY__"
__NAMESERVERS_BLOCK__
